Credit Card Fraud Detection::

Download dataset from this link:

https://www.kaggle.com/mlg-ulb/creditcardfraud

Description about dataset::
The datasets contains transactions made by credit cards in September 2013 by european cardholders. This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.

It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, … V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-senstive learning.
Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.¶

WORKFLOW :
1.Load Data

2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

3.Standardized the Input Variables.

4.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

5.Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).

6.Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)

7.Train the Model with Epochs (100).

8.If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .

9.Prediction should be > 92% 10.Evaluation Step 11Prediction

Task::
Identify fraudulent credit card transactions.¶

In [ ]:
import numpy as np
import pandas as pd
Card_csv = pd.read_csv("./drive/MyDrive/Dl_Assignments/DLAssignments/creditcard.csv")

In [ ]:
Card_csv.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [ ]:
Card_csv.isnull()

Time     V1     V2     V3     V4  ...    V26    V27    V28  Amount  Class
0       False  False  False  False  False  ...  False  False  False   False  False
1       False  False  False  False  False  ...  False  False  False   False  False
2       False  False  False  False  False  ...  False  False  False   False  False
3       False  False  False  False  False  ...  False  False  False   False  False
4       False  False  False  False  False  ...  False  False  False   False  False
...       ...    ...    ...    ...    ...  ...    ...    ...    ...     ...    ...
284802  False  False  False  False  False  ...  False  False  False   False  False
284803  False  False  False  False  False  ...  False  False  False   False  False
284804  False  False  False  False  False  ...  False  False  False   False  False
284805  False  False  False  False  False  ...  False  False  False   False  False
284806  False  False  False  False  False  ...  False  False  False   False  False

[284807 rows x 31 columns]

In [ ]:
np.where(Card_csv.applymap(lambda x: x==""))

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
Card_csv.describe()

Time            V1  ...         Amount          Class
count  284807.000000  2.848070e+05  ...  284807.000000  284807.000000
mean    94813.859575  3.919560e-15  ...      88.349619       0.001727
std     47488.145955  1.958696e+00  ...     250.120109       0.041527
min         0.000000 -5.640751e+01  ...       0.000000       0.000000
25%     54201.500000 -9.203734e-01  ...       5.600000       0.000000
50%     84692.000000  1.810880e-02  ...      22.000000       0.000000
75%    139320.500000  1.315642e+00  ...      77.165000       0.000000
max    172792.000000  2.454930e+00  ...   25691.160000       1.000000

[8 rows x 31 columns]

In [ ]:
np.random.seed(123)
mask= np.random.rand(len(Card_csv)) < 0.7
train = Card_csv[mask]
test = Card_csv[~mask]

In [ ]:
print(train.shape)
print(test.shape)

(199077, 31)
(85730, 31)


In [ ]:
train_l = train.iloc[:,-1]
test_l = test.iloc[:,-1]

In [ ]:
train_l.shape

(199077,)

In [ ]:
train_data = train.drop(columns = 'Class')

In [ ]:
train_data

Time         V1         V2  ...       V27       V28  Amount
0            0.0  -1.359807  -0.072781  ...  0.133558 -0.021053  149.62
1            0.0   1.191857   0.266151  ... -0.008983  0.014724    2.69
2            1.0  -1.358354  -1.340163  ... -0.055353 -0.059752  378.66
3            1.0  -0.966272  -0.185226  ...  0.062723  0.061458  123.50
5            2.0  -0.425966   0.960523  ...  0.253844  0.081080    3.67
...          ...        ...        ...  ...       ...       ...     ...
284801  172785.0   0.120316   0.931005  ...  0.217940  0.068803    2.69
284802  172786.0 -11.881118  10.071785  ...  0.943651  0.823731    0.77
284803  172787.0  -0.732789  -0.055080  ...  0.068472 -0.053527   24.79
284805  172788.0  -0.240440   0.530483  ...  0.108821  0.104533   10.00
284806  172792.0  -0.533413  -0.189733  ... -0.002415  0.013649  217.00

[199077 rows x 30 columns]

In [ ]:
test_data = test.drop(columns='Class')

In [ ]:
test_data

Time        V1        V2  ...       V27       V28  Amount
4            2.0 -1.158233  0.877737  ...  0.219422  0.215153   69.99
6            4.0  1.229658  0.141004  ...  0.034507  0.005168    4.99
11          10.0  0.384978  0.616109  ...  0.042472 -0.054337    9.99
15          12.0 -0.752417  0.345485  ... -0.180998  0.129394   15.99
21          17.0  0.962496  0.328461  ...  0.016371 -0.014605   34.09
...          ...       ...       ...  ...       ...       ...     ...
284787  172769.0 -1.029719 -1.110670  ...  0.025271  0.255347    9.99
284789  172770.0 -0.446951  1.302212  ...  0.503092  0.229921   60.50
284792  172774.0 -0.724123  1.485216  ... -0.170579 -0.030692    3.99
284798  172782.0  0.219529  0.881246  ...  0.181205  0.215243   24.05
284804  172788.0  1.919565 -0.301254  ...  0.004455 -0.026561   67.88

[85730 rows x 30 columns]

In [ ]:
m = train_data.mean(axis=0)
train_data -= m
std = train_data.std(axis=0)
train_data /= std
test_data -= m
test_data /= std

MODELS SECTION 

In [ ]:
from keras import models, layers
model = models.Sequential()
model.add(layers.Dense(20, activation='relu',input_shape=(train_data.shape[1],)))
#model.add(layers.Dropout(0.5))
model.add(layers.Dense(10, activation='relu'))
#model.add(layers.Dropout(0.5))
model.add(layers.Dense(8, activation='relu'))
#model.add(layers.Dropout(0.5))
model.add(layers.Dense(6, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
#model.add(layers.Dense(8, activation= act))
#model.add(layers.Dense(6, activation= act))
#model.add(layers.Dense(1))
#model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
#return model

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(train_data, train_l, epochs=100, validation_split=0.3, validation_batch_size=150, validation_steps=10)

Epoch 1/100
4355/4355 [==============================] - 7s 1ms/step - loss: 0.1056 - accuracy: 0.9599 - val_loss: 0.0010 - val_accuracy: 1.0000
Epoch 2/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0037 - accuracy: 0.9992 - val_loss: 6.1513e-04 - val_accuracy: 1.0000
Epoch 3/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0030 - accuracy: 0.9993 - val_loss: 7.2079e-04 - val_accuracy: 1.0000
Epoch 4/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0027 - accuracy: 0.9993 - val_loss: 4.7826e-04 - val_accuracy: 1.0000
Epoch 5/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0024 - accuracy: 0.9993 - val_loss: 8.2330e-04 - val_accuracy: 1.0000
Epoch 6/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0024 - accuracy: 0.9994 - val_loss: 3.9838e-04 - val_accuracy: 1.0000
Epoch 7/100
4355/4355 [==============================] - 6s 1ms/step - loss: 0.0020 - accuracy: 0.9993 - val_l

In [ ]:
loss, accuracy = model.evaluate(test_data, test_l)

2680/2680 [==============================] - 3s 943us/step - loss: 0.0182 - accuracy: 0.9993


In [ ]:
test_data.shape

(85730, 30)

In [ ]:
model.predict(np.array(test_data.iloc[1,:]).reshape(1, test_data.shape[1]))

array([[2.5738887e-18]], dtype=float32)

In [ ]:
x = model.predict(test_data)

In [ ]:
max(x)

array([1.], dtype=float32)

In [ ]:
x[0:10]

array([[4.5054455e-16],
       [2.5738986e-18],
       [1.1800568e-21],
       [4.1574864e-32],
       [0.0000000e+00],
       [2.2428338e-21],
       [4.6682283e-37],
       [4.4194724e-28],
       [0.0000000e+00],
       [7.7889107e-36]], dtype=float32)

In [ ]:
test_l[:10]

4     0
6     0
11    0
15    0
21    0
22    0
24    0
37    0
38    0
44    0
Name: Class, dtype: int64